apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: github-actions-runner
  name: github-actions-runner
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
      - env:
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GITHUB_ACCESS_TOKEN
          value: YOUR_TOKEN
        - name: RUNNER_REPOSITORY_URL
          value: YOUR_REPOSITORY_URL
        image: tcardonne/github-runner:latest
        imagePullPolicy: Always
        name: runner
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
